### ISSUE TITLE
To many enter press on ctrl-R search

### ISSUE THREAD

**Issue by doubleloop** [psprint/zsh-navigation-tools#14]
Hi,
I understand the idea of enter/escape key press to escape search modee. But in case of using n-history as ctrl+R replacement, IMO there is no need to press enter 1 extra time for exiting search mode. All you want to do in 99% of cases is to re-execute/modify found command and thus only one enter key press would suffice (right now you have to press it 2 times and then once more to run the command).

Actually what are the reasons for having non search mode (beside the fact that you can navigate  with jk)?

**Comment by psprint** [comment]
Logically I agree. Had the same thoughts. But when I started to use n-history myself, just to "feel" it if it behaves right, I've found the enter strokes to be quite good for finger memory. One extra enter is also a nice barrier for not executing a command accidentally. Will think about adding configuration option for what you report, so that enter moves user straight to command line, because it might be that what the barrier against accidental execution actually is, is serious change of view – command line is shown instead of full screen list of history entries – that might induce enough alertness in user so that he will not run command too fast.

**Comment by doubleloop** [comment]
+1 for configuration option

**Comment by jasontibbitts** [comment]
I found the extra keystrokes to be a bit too much.  I really wish for something much simpler, that works more like tab completion with a few options shown below the prompt instead of a complete interface.  Haven't found anything yet, but I haven't really looked all that hard.

**Comment by doubleloop** [comment]
IMO the full interface is really cool.
@jasontibbitts have you try https://github.com/zsh-users/zsh-autosuggestions?

**Comment by jasontibbitts** [comment]
I have, actually.  It's not bad, but I still find myself grepping ~/.zshhist far too often.

**Comment by psprint** [comment]
I've added the configuration option. For new users, following block will exist in n-history.conf:

```zsh
# When 1, pressing enter when in search mode will not
# only leave the mode, but also do selection and leave
# n-history
local NLIST_INSTANT_SELECT=0
```

Existing users need to add it to ~/.config/znt/n-history.conf. And change the variable to "1" if instant selection is desired.

**Comment by jasontibbitts** [comment]
I'm really liking this now.

**Comment by doubleloop** [comment]
One more thing concerning oh-my-zsh and configuration. You have your own config files copied to `~/.config/znt/`, and  I do not see the way to propagate configuration from zshrc..  It would be awesome If such flags could be set in zshrc (so all custom configuration is in one place and easy to deploy/share).

**Comment by psprint** [comment]
@doubleloop: could you create new issue for this?

**Comment by doubleloop** [comment]
I did, https://github.com/robbyrussell/oh-my-zsh/issues/5064

**Comment by jasontibbitts** [comment]
Not sure why that's filed under oh-my-zsh instead of here, though.
